[package]
name = "voxxelmaxx"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
avian3d = "0.6.1"
bevy = { version = "0.18.1", default-features = false, features = ["3d"] }
bitvec = "1.0.1"
dot_vox = "5.2.0"
# noisy_bevy = { path = "../../clones/noisy_bevy" }
rand = "0.10.1"

[dev-dependencies]
bevy-inspector-egui = "0.36.0"
