[package]
name = "voxxelmaxx"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
avian3d = { git = "https://github.com/stuartparmenter/avian.git", branch = "bevy-0.19" }
bevy = { git = "https://github.com/akriegman/bevy.git", rev = "9460762", default-features = false, features = ["3d"] }
bitvec = "1.0.1"

[dev-dependencies]
rand = "0.10.1"

[patch.crates-io]
parry3d = { git = "https://github.com/akriegman/parry", branch = "master" }

[patch.'https://github.com/bevyengine/bevy']
bevy = { git = "https://github.com/akriegman/bevy.git", rev = "9460762" }
bevy_math = { git = "https://github.com/akriegman/bevy.git", rev = "9460762" }
bevy_reflect = { git = "https://github.com/akriegman/bevy.git", rev = "9460762" }
